# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm install -g serverless
      npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
    displayName: 'npm install and serverless install'
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '18.06.3-ce'
    displayName: 'Install Docker'
  - task: AWSShellScript@1
    inputs:
        awsCredentials: 'ecarbon-cp'
        regionName: $(AWS_REGION)
        scriptType: 'inline'
        inlineScript: |
          serverless package -t $(CG_ID):$(CG_SECRET)
    displayName: 'Run Serverless package'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/cloudguard_output'
      artifact: 'cloudguard_output'
      publishLocation: 'pipeline'
    displayName: 'Publishing Artifacts'